c1 = list(input().split())
c2 = list(input().split())
c3 = list(input().split())
c4 = list(input().split())
c1.reverse()
c2.reverse()
c3.reverse()
c4.reverse()

print(" ".join(c4))
print(" ".join(c3))
print(" ".join(c2))
print(" ".join(c1))
